name: Gatobot


on: push

 #   schedule:

 #       - cron: '0 10 * * *'


jobs:
  tweet:
    name: Insta
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõé
        uses: actions/checkout@v3
        
      - name: Keep this repo alive
        uses: gautamkrishnar/keepalive-workflow@master

      - name: Set up Python üêç
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache Python packages üíæ
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install packages ‚öô
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if instacat_session exists
        id: session-check
        run: echo "::set-output name=exists::$(if [ -f instacat_session.json ]; then echo 'true'; else echo 'false'; fi)"

      - name: Download Instagram Session
        if: steps.session-check.outputs.exists == 'true'
        uses: actions/download-artifact@v3
        with:
          name: instacat_session
          path: .

      - name: Create empty session file if not exists
        if: steps.session-check.outputs.exists == 'false'
        run: echo '{}' > instacat_session.json

      # Use HEREDOC for `run` to escape possible single and double quotes in the message.
      - name: cat story üê±
        env:
                  USERNAME: ${{ secrets.USERNAME }}

                  PASSWORD: ${{ secrets.PASSWORD }}

                  CAT_KEY: ${{ secrets.CAT_KEY }}

                  TELE_USER: ${{ secrets.TELE_USER }}

                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

                  GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}
                  
        run: python botgram.py

      - name: Upload Instagram Session
        uses: actions/upload-artifact@v3
        with:
          name: instacat_session
          path: instacat_session.json
